Improved the UI of loklak.org/settings
fossasia/loklak_search pull request #921
Opened 2018-09-29 23:24 UTC by rajvaibhavdubey

Improved the UI of the settings page, UI inspired from the site itself.

Fixes #1919

**Changes proposed in this pull request**
- The UI of the loklak.org/settings has been improved

**Screenshots** 
![loklak-settings](https://user-images.githubusercontent.com/33062425/46251289-ab0bf600-c46c-11e8-9522-566e4e2ed221.png)

**Closes #919**

2018-10-02 10:28 UTC, simsausaurabh requested changes
@rajvaibhavdubey Please check travis, there are some style issues.

2018-10-05 10:17 UTC, rajvaibhavdubey commented
@simsausaurabh Could you please guide me about travis fixes, I'm not able to pinpoint the error

2018-10-05 10:22 UTC, simsausaurabh commented
@rajvaibhavdubey Run command: ```ng lint loklak-search --format=stylish``` in your current project directory and fix the lint issues which shows up :+1:

2018-10-13 05:45 UTC, simsausaurabh commented
@rajvaibhavdubey Please provide a test link to check your current changes.

2018-10-13 05:46 UTC, simsausaurabh commented on src/app/settings/settings.component.scss
> +}
Add EOF.

2018-10-13 05:47 UTC, simsausaurabh commented on src/app/settings/settings.component.html
> +<app-footer></app-footer>
Add EOF.

2018-10-13 05:48 UTC, simsausaurabh commented on src/app/settings/settings.component.spec.ts
> +
Unnecessary line space.

2018-10-13 05:48 UTC, simsausaurabh commented on src/app/settings/settings.component.spec.ts
> +
Unnecessary line space.

2018-10-13 05:48 UTC, simsausaurabh commented on src/app/settings/settings.component.scss
> +	right: 0;
Do we really require ```0``` values?

2018-12-10 13:25 UTC, simsausaurabh commented
Closing this PR due to inactivity. Follow up once available.

2018-12-10 13:25 UTC, closed without merging