Redesigining Loklak Search Settings
fossasia/loklak_search pull request #926
Opened 2018-11-01 17:39 UTC by sk9331657

**Changes proposed in this pull request**
- Redesign

**Screenshots (if appropriate)** 

**Link to live demo: ** 

**Closes #924**

2018-11-02 06:24 UTC, championpaddler commented
@simsausaurabh Please review.

2018-11-02 16:05 UTC, sk9331657 commented
@simsausaurabh @praveenojha33 @daminisatya @gabru-md @ParthS007 Please review.

2018-11-03 10:01 UTC, simsausaurabh commented on src/app/settings/settings.component.html
> +<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin=
Isn't bootstrap already included in root html file?

2018-11-03 10:01 UTC, simsausaurabh commented on src/app/settings/settings.component.html
> +      <h2>{{key[0]|uppercase}}</h2>
Keep proper spacing

2018-11-03 10:01 UTC, simsausaurabh commented on src/app/settings/settings.component.html
> +</div>
Add EOF.

2018-11-03 10:01 UTC, simsausaurabh commented on src/app/settings/settings.component.scss
> +}
Add EOF.

2018-11-03 10:02 UTC, simsausaurabh commented on src/app/settings/settings.component.scss
> +    transition: 0.3s;
Please follow proper indentation

2018-11-03 10:02 UTC, simsausaurabh commented on src/app/settings/settings.component.scss
> +    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
Please fix it too.

2018-11-03 10:02 UTC, simsausaurabh requested changes
Please fix inlines.

2018-11-06 10:01 UTC, sk9331657 commented
@simsausaurabh

2018-11-06 10:54 UTC, simsausaurabh requested changes
Please do not mark the requested changes as resolved when they are not already resolved.

2018-11-07 05:10 UTC, sk9331657 commented
@simsausaurabh  Can you please review this one and highlight the required changes??

2018-11-10 13:53 UTC, sk9331657 commented
@simsausaurabh  @praveenojha33  Please review.

2018-11-10 14:03 UTC, simsausaurabh commented
@sk9331657 Could you please provide any other deployment link apart from surge ?

2018-11-10 14:39 UTC, sk9331657 commented
@simsausaurabh  Sure

2018-11-10 14:59 UTC, sk9331657 commented
@simsausaurabh  http://fervent-bohr-61e734.netlify.com/

2018-11-10 15:03 UTC, sk9331657 commented
@simsausaurabh  Seems like it needs to be hosted on heroku for testing since routing is done on frontend.

2018-11-10 15:35 UTC, simsausaurabh commented
@sk9331657 Could you set it up once and for all on Heroku to even test your further PRs?

2018-11-10 15:37 UTC, simsausaurabh commented
@sk9331657 Please follow: https://medium.com/@hellotunmbi/how-to-deploy-angular-application-to-heroku-1d56e09c5147 for deploying (Angular project) on Heroku.

2018-11-10 15:38 UTC, sk9331657 commented
> @sk9331657 Please follow: https://medium.com/@hellotunmbi/how-to-deploy-angular-application-to-heroku-1d56e09c5147 for deploying (Angular project) on Heroku.

@simsausaurabh  I will deploy the pr's.

2018-11-11 06:48 UTC, sk9331657 commented
@simsausaurabh  Preview https://loklaktest.herokuapp.com/settings

2018-11-11 06:49 UTC, sk9331657 commented
@simsausaurabh  Please review.

2018-11-11 06:49 UTC, sk9331657 commented
@praveenojha33  Review.

2018-11-11 07:50 UTC, simsausaurabh commented
@sk9331657 Please make active links: e.g. ```root```, etc inactive. And show the other active URLs like: ```fossasia.org``` instead of ```https://fossasia.org```, it should work as usual but it should not display other non useful matter e.g. https. Make background a little bit grey (not primarily, nor purely white) something like: 

![screenshot from 2018-11-11 13-18-40](https://user-images.githubusercontent.com/16608864/48310382-666b9280-e5b4-11e8-858f-b69dcc314b39.png)

2018-11-12 17:03 UTC, sk9331657 commented
@simsausaurabh  Can you please review https://loklaktest.herokuapp.com/settings ??

2018-11-13 03:59 UTC, simsausaurabh commented
@sk9331657 Yes, it has improved a lot, good work. Can you shorten the URLs too as mentioned in above comment by me. News Configuration card on bottom looks a bit odd, comparing to others.

2018-11-14 17:57 UTC, sk9331657 commented
@simsausaurabh @praveenojha33 Please review now.

2018-11-14 23:45 UTC, praveenojha33 requested changes
@sk9331657 Please fix travis.

2018-11-15 09:20 UTC, sk9331657 commented
@simsausaurabh  Please review now.

2018-11-15 10:48 UTC, sk9331657 commented
@praveen @simsausaurabh  please review and merge this now.

2018-11-15 17:33 UTC, sk9331657 commented
@simsausaurabh  @praveenojha33

2018-11-16 05:35 UTC, sk9331657 commented
@mario Can you please review??

2018-11-19 17:34 UTC, praveenojha33 commented
@sk9331657 Please update the corresponding issue. Please add more information to the issue so that everyone can easily understand the issue and review the corresponding PR. :+1:

2018-11-19 17:36 UTC, praveenojha33 commented
Please also update the surge link to heroku link in PR description.

2018-11-19 17:39 UTC, praveenojha33 commented
Rest other things looks good to me. Please update issue and PR description so that it will be easy for everyone else to review your PR.

2018-11-21 12:14 UTC, sk9331657 commented
> Rest other things looks good to me. Please update issue and PR description so that it will be easy for everyone else to review your PR.

Done @praveenojha33  . Please review.

2018-11-21 12:14 UTC, sk9331657 commented
@simsausaurabh  Please review.

2018-11-22 12:38 UTC, sk9331657 commented
@fossasia/loklak-devs  Please review.

2018-11-22 14:19 UTC, simsausaurabh approved these changes
For start, it looks good to me.
@mariobehling Please review.

2018-11-22 14:20 UTC, simsausaurabh commented
@sk9331657 Please also update the required details in issue description.

2018-11-24 07:30 UTC, sk9331657 commented
@mariobehling  @simsausaurabh Please review.

2018-11-25 18:22 UTC, praveenojha33 approved these changes
LGTM :+1:

2018-12-08 14:39 UTC, sk9331657 commented
@simsausaurabh  Reviews??

2018-12-10 13:17 UTC, sk9331657 commented
@mariobehling  Please review and merge this.

2018-12-10 13:21 UTC, simsausaurabh commented
@sk9331657 It looks good for start. Please update the issue description which you are currently solving.

@mariobehling Please review.

2018-12-22 08:54 UTC, sk9331657 commented
@simsausaurabh  i have updated the issue description.

2018-12-22 09:22 UTC, simsausaurabh commented
Your deployment isn't active anymore?

2018-12-22 09:27 UTC, championpaddler commented
@simsausaurabh  DO I redeploy as heroku has limit of 5 project so I deployed other project??

2018-12-22 09:31 UTC, simsausaurabh commented
I have requested review from @mariobehling. Please also mention the PR link on Gitter. Yes, please redeploy.

2018-12-23 09:18 UTC, sk9331657 commented
@mariobehling  Please review. Here is deployment link http://agorawebapp.herokuapp.com/

2018-12-26 18:41 UTC, sk9331657 commented
@mariobehling  Can you please review this?? This is pending since long time.

2019-01-15 17:52 UTC, sk9331657 commented
@mariobehling  Please review this also .

2019-02-19 16:58 UTC, simsausaurabh commented
@sk9331657 Lets keep it on hold for a while. I will discuss it with co-developers and then we will decide how to proceed with this. Feel free to discuss about it on Gitter.

2019-02-19 16:58 UTC, closed without merging