Added sidebar menu on Privacy page
fossasia/loklak_search pull request #942
Opened 2018-12-19 19:47 UTC by shreyanshdwivedi

**Changes proposed in this pull request**
- Added sidebar on `Privacy` page

**Screenshots (if appropriate)** 
![screenshot_2018-12-20 loklak search - distributed search for twitter and social media with peer to peer technology](https://user-images.githubusercontent.com/25428397/50244060-f80cc200-03f4-11e9-91e4-8e01b78d2d18.png)

**Link to live demo: ** 

**Related to #937**

2018-12-19 20:04 UTC, shreyanshdwivedi commented
@praveenojha33 @simsausaurabh please review :)

2018-12-22 09:25 UTC, simsausaurabh reviewed
Add EOF and rest is good.

2018-12-22 09:25 UTC, simsausaurabh commented on src/app/privacy/privacy.component.html
> +	<app-footer></app-footer>
Add EOF.

2018-12-22 12:07 UTC, shreyanshdwivedi commented
@simsausaurabh @praveenojha33 please review :)

2018-12-24 00:47 UTC, praveenojha33 approved these changes
LGTM :+1:

2018-12-24 09:59 UTC, simsausaurabh requested changes
Margin between main screen content from side bar on Privacy page is smaller than compared to your other PR which adds sidebar on Terms page. Please change the current one to be similar to the one on Terms page.

2018-12-24 14:47 UTC, shreyanshdwivedi commented
@simsausaurabh I've made the required changes and squashed the commits too. Please review :)

2018-12-29 14:39 UTC, simsausaurabh commented
Resolve conflicts.

2018-12-30 13:10 UTC, shreyanshdwivedi commented
@simsausaurabh I've resolved the conflicts. Please merge :))

2018-12-30 14:29 UTC, simsausaurabh commented
Squash your commits too, then it will be good to go.

2018-12-30 18:37 UTC, shreyanshdwivedi commented
@simsausaurabh I've squashed the commits. Please check :)

2018-12-31 05:44 UTC, simsausaurabh approved these changes

2018-12-31 05:44 UTC, merged