Adds tests for feed-linker and feed-footer component
fossasia/loklak_search pull request #946
Opened 2019-01-03 17:59 UTC by shreyanshdwivedi

**Changes proposed in this pull request**
- Adds tests for feed-linker and feed-footer component

**Screenshots (if appropriate)** 

**Link to live demo: **  http://pr-946-fossasia-loklaksearch.surge.sh

**Related to #414**

2019-01-03 18:07 UTC, shreyanshdwivedi commented
@simsausaurabh @praveenojha33 please review

2019-01-04 04:20 UTC, simsausaurabh approved these changes

2019-01-05 07:20 UTC, sakshee-19 approved these changes

2019-01-09 21:19 UTC, shreyanshdwivedi commented
@praveenojha33 please review

2019-01-14 16:17 UTC, praveenojha33 approved these changes

2019-01-14 17:29 UTC, shreyanshdwivedi commented
@simsausaurabh please merge

2019-01-15 15:13 UTC, simsausaurabh requested changes
Make one change.

2019-01-15 15:13 UTC, simsausaurabh commented on src/app/feed/feed-linker/feed-linker.component.spec.ts
> +			'fossasia',
hashtags to be given should be: ```FOSSASIA```. We follow this in our tweets too.

2019-01-15 15:39 UTC, shreyanshdwivedi commented
@simsausaurabh please review

2019-01-15 16:48 UTC, simsausaurabh approved these changes

2019-01-15 16:51 UTC, simsausaurabh commented
@shreyanshdwivedi For your future PRs for increasing test coverage try only to add something meaningful to test since you have got familiar with writing test cases for the current codebase.

2019-01-15 16:52 UTC, merged