Updates dropdown menu
fossasia/loklak_search pull request #956
Opened 2019-02-04 22:01 UTC by abhijeetyadav82

**Changes proposed in this pull request**
- Added the meilix project.
- Fixed the badgeyay icon.

**Screenshots (if appropriate)** 
![screenshot from 2019-02-05 09-01-02](https://user-images.githubusercontent.com/32612741/52240296-803c1d80-28f6-11e9-82c5-d1d2b3983eb3.png)

**Link to live demo: ** 

**Closes #955 **

2019-02-05 06:23 UTC, shreyanshdwivedi approved these changes
LGTM :+1:

2019-02-05 09:23 UTC, rajvaibhavdubey approved these changes
LGTM :+1:

2019-02-08 18:04 UTC, simsausaurabh commented on src/app/service-box/service-box.component.html
> +
Remove extra line

2019-02-08 21:09 UTC, plxity approved these changes

2019-03-19 02:42 UTC, singhpratyush requested changes
The text for `meilix generator` overlaps the image on Chrome (haven't checked other browsers) - 

![Screenshot from 2019-03-19 08-09-20](https://user-images.githubusercontent.com/10860278/54576547-af2dcf00-4a1e-11e9-80ce-0209b01e1b9c.png)

2019-07-16 05:57 UTC, simsausaurabh commented
Closing due to inactivity. Please follow up with new PR.

2019-07-16 05:57 UTC, closed without merging